# Generated by Django 3.1.8 on 2021-05-08 17:13

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hordak', '0032_auto_20210508_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leg',
            name='amount_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('BTC', 'Bitcoin'), ('ADA', 'Cardano'), ('COMP', 'Compound'), ('ETH', 'Ethereum'), ('KRILL', 'Krill'), ('DAI', 'Makerdao'), ('NANO', 'Nano'), ('MATIC', 'Polygon (MATIC)'), ('SHIB', 'Shiba Token'), ('USDT', 'Tether'), ('USD', 'USD')], default='EUR', editable=False, max_length=20),
        ),
    ]
