# Generated by Django 3.1.8 on 2021-05-06 12:54

from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hordak', '0046_auto_20210505_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leg',
            name='amount',
            field=djmoney.models.fields.MoneyField(decimal_places=15, default_currency='EUR', help_text='Record debits as positive, credits as negative', max_digits=30, verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='leg',
            name='amount_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'EURC'), ('ETH', 'Ethereum T'), ('DAI', 'Makerdao'), ('SHIB', 'Shiba Token'), ('USD', 'USD $')], default='EUR', editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='statementline',
            name='amount',
            field=models.DecimalField(decimal_places=15, max_digits=30, verbose_name='amount'),
        ),
    ]
